@echo off
setlocal enabledelayedexpansion

REM ==============================================================================
REM  Install Game Performance Manager to Windows Startup
REM  Creates VBS script and places it in shell:startup for automatic boot startup
REM ==============================================================================

title Install Game Performance Manager Startup

echo.
echo ========================================
echo  Install Game Performance Manager
echo       to Windows Startup
echo ========================================
echo.

REM Get current script directory (where the silent script is located)
set "SCRIPT_DIR=%~dp0"
set "SILENT_SCRIPT_PATH=%SCRIPT_DIR%GamePerformanceManagerSilent.bat"

echo [INFO] Script directory: %SCRIPT_DIR%
echo [INFO] Silent script path: %SILENT_SCRIPT_PATH%
echo.

REM Check if the silent script exists
if not exist "%SILENT_SCRIPT_PATH%" (
    echo [ERROR] GamePerformanceManagerSilent.bat not found!
    echo Please ensure this installer is in the same folder as GamePerformanceManagerSilent.bat
    pause
    exit /b 1
)

REM Get Windows startup folder path
for /f "usebackq tokens=3*" %%A in (`reg query "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders" /v Startup 2^>nul`) do (
    set "STARTUP_FOLDER=%%A %%B"
)

REM Fallback if registry lookup fails
if not defined STARTUP_FOLDER (
    set "STARTUP_FOLDER=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup"
)

echo [INFO] Windows startup folder: %STARTUP_FOLDER%
echo.

REM Check if startup folder exists
if not exist "%STARTUP_FOLDER%" (
    echo [ERROR] Windows startup folder not found: %STARTUP_FOLDER%
    echo Please check your Windows installation
    pause
    exit /b 1
)

REM Define VBS script name and path
set "VBS_NAME=GamePerformanceManager_Startup.vbs"
set "VBS_PATH=%STARTUP_FOLDER%\%VBS_NAME%"

echo [ACTION] Creating VBS startup script...
echo [TARGET] %VBS_PATH%
echo.

REM Create the VBS file using simple echo statements
echo ' ============================================== > "%VBS_PATH%"
echo ' HP Omen Game Performance Manager (Hidden^) >> "%VBS_PATH%"
echo ' Starts the manager completely in background >> "%VBS_PATH%"
echo ' Auto-generated by InstallStartup.bat >> "%VBS_PATH%"
echo ' ============================================== >> "%VBS_PATH%"
echo. >> "%VBS_PATH%"
echo Set objShell = CreateObject("WScript.Shell"^) >> "%VBS_PATH%"
echo Set objFSO = CreateObject("Scripting.FileSystemObject"^) >> "%VBS_PATH%"
echo. >> "%VBS_PATH%"
echo ' Auto-detected path to your OmenMon Bkg folder >> "%VBS_PATH%"
echo strScriptPath = "%SCRIPT_DIR:~0,-1%" >> "%VBS_PATH%"
echo strBatchFile = strScriptPath ^& "\GamePerformanceManagerSilent.bat" >> "%VBS_PATH%"
echo. >> "%VBS_PATH%"
echo ' Check if the main script exists >> "%VBS_PATH%"
echo If objFSO.FileExists(strBatchFile^) Then >> "%VBS_PATH%"
echo     ' Set working directory and run the batch file hidden >> "%VBS_PATH%"
echo     objShell.CurrentDirectory = strScriptPath >> "%VBS_PATH%"
echo     objShell.Run """" ^& strBatchFile ^& """", 0, False >> "%VBS_PATH%"
echo Else >> "%VBS_PATH%"
echo     ' Show error message if file not found >> "%VBS_PATH%"
echo     objShell.Popup "ERROR: GamePerformanceManagerSilent.bat not found!" ^& vbCrLf ^& _ >> "%VBS_PATH%"
echo                   "Location: " ^& strScriptPath ^& vbCrLf ^& _ >> "%VBS_PATH%"
echo                   "Please ensure all files are in the same directory.", _ >> "%VBS_PATH%"
echo                   10, "Game Performance Manager", 16 >> "%VBS_PATH%"
echo End If >> "%VBS_PATH%"
echo. >> "%VBS_PATH%"
echo Set objShell = Nothing >> "%VBS_PATH%"
echo Set objFSO = Nothing >> "%VBS_PATH%"

if errorlevel 1 (
    echo [ERROR] Failed to create VBS script in startup folder
    echo You may need to run this as Administrator
    pause
    exit /b 1
)

echo [SUCCESS] VBS startup script created successfully!
echo.
echo ========================================
echo           INSTALLATION COMPLETE
echo ========================================
echo.
echo The Game Performance Manager will now automatically start when Windows boots.
echo.
echo Details:
echo --------
echo Script Name: %VBS_NAME%
echo Location: %VBS_PATH%
echo Target: %SILENT_SCRIPT_PATH%
echo.
echo What happens on startup:
echo - VBS script launches silently (no window)
echo - Silent batch script runs in background
echo - Game monitoring begins automatically
echo - No user interaction required
echo.
echo To UNINSTALL:
echo - Delete: %VBS_PATH%
echo - Or run: UninstallStartup.bat (if available)
echo.
echo [INFO] Testing the startup script...

REM Test the VBS script
echo [TEST] Launching VBS script to test...
cscript //nologo "%VBS_PATH%" 2>nul
if errorlevel 1 (
    echo [WARNING] VBS script test failed, but installation completed
    echo The script should still work on Windows startup
) else (
    echo [SUCCESS] VBS script test passed
)

echo.
echo Installation completed successfully!
echo The Game Performance Manager will start automatically on next Windows boot.
echo.
pause
